# run the evaluation of a robot controller and store the result in the participants.txt file

name: Run Evaluation

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  evaluation:
    name: Evaluation Requested by a Participant
    runs-on: ubuntu-20.04
    steps:
      - name: Is repo link actually a repo?
        id: repo_check
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          gh api --silent -H "Accept: application/vnd.github+json" /repos/${{ github.event.client_payload.repository }}
        continue-on-error: true
      - name: If repo not visible, is there a collaboration invite?
        if: steps.repo_check.outcome == 'failure'
        id: invites_check
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          invite_id=$( \
            gh api -H "Accept: application/vnd.github+json" \
              /user/repository_invitations | jq '.[] | select(.repository.full_name=="${{ github.event.client_payload.repository }}") | .id' \
          )
          echo $invite_id
          gh api --silent --method PATCH -H "Accept: application/vnd.github+json" /user/repository_invitations/$invite_id
      - name: Get Participant Repository ID
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          repo_id=$( gh api -H "Accept: application/vnd.github+json" /repos/${{ github.event.client_payload.repository }} | jq '.id' )
          echo "PARTICIPANT_REPO_ID=$repo_id" >> $GITHUB_ENV
          echo "participant repository: ${{ github.event.client_payload.repository }}"
      - name: Checkout the Organizer Repository
        uses: actions/checkout@v3
      - name: Record Animation and Update Performance
        timeout-minutes: 10
        id: webots_test
        uses: cyberbotics/competition-record-action@main
        env:
          INPUT_INDIVIDUAL_EVALUATION: ${{ format('{0}:{1}', env.PARTICIPANT_REPO_ID, github.event.client_payload.repository) }}
          INPUT_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          INPUT_ALLOW_PUSH: True
      - name: Feedback on Failure
        if: failure() || cancelled()
        uses: actions-ecosystem/action-create-issue@v1.0.0
        with:
          repo: ${{ github.event.client_payload.repository }}
          github_token: ${{ github.token }}
          title: Failure
          body: |
            There was a problem with your controller program.
            Look at the [action logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
          labels: bug
      - name: Free Queue and Possibly Trigger New Workflow
        if: always()
        run: |
          curl -s -X POST -F 'organizer=${{ github.repository }}' -F'participant=${{ github.event.client_payload.repository }}' -F'organizer_repo_token=${{ github.token }}' https://webots.cloud/run_competition.php
