name: triggers a run action on the repository of the organizer

on:
  push:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Create a repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          gh api repos/cyberbotics/wrestling/dispatches --raw-field event_type=run_trigger
