# Triggers a run action on the repository of the organizer when the robot controller get modified on the main branch

name: Controller Evaluation

on:
  push:
    branches:
      - master
    paths:
      - controllers/edit_me/**

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Create a repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          gh api repos/ORGANIZER_NAME/ORGANIZER_REPOSITORY/dispatches --raw-field event_type=run_trigger
