# Triggers a run action on the repository of the organizer when the robot controller get modified on the main branch

name: Trigger Evaluation

on:
  push:
    branches:
      #- main
      - disabled
    paths:
      - controllers/**

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Send a repository dispatch event from the webots-cloud GitHub user
        run: |
          curl "https://webots.cloud/benchmark.php?organizer=cyberbotics/benchmark-template&participant=${{ github.repository }}"
