# Triggers a run action on the repository of the organizer when the robot controller get modified on the main branch

name: Controller Evaluation

on:
  push:
    branches:
      - master
    paths:
      - controllers/**

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Create a repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
        run: |
          curl -d '{"event_type": "run_trigger", "client_payload": {"repository": "${{ github.repository }}"}}' -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/cyberbotics/benchmark-template/dispatches"
